# ===================================================
# SERL Mock Data - General Configuration
# ===================================================

# -------------------------
# Global
# -------------------------
n_households: 100
seed: 42
edition: "08"

# -------------------------
# Time period for smart-meter data
# -------------------------
start_year: 2019
end_year: 2019